const express = require('express')
const router = express.Router()
const { viewUlasan, getCode, addUlasan, deleteUlasan } = require('../controller/ulasanController')
const { upload, viewProduk, addProduk, deleteProduk, updateProduk } = require('../controller/produkController')
const { viewPageSetting, updatePage } = require('../controller/pageController')
const { viewIndex, artikelBlogView } = require('../controller/indexController')
const { authView, auth, updateView, updateUser, logout } = require('../controller/authController')
const { protectRoute, redirectRoute } = require('../auth/authview')
const { viewArtikel, addArtikel, updateArtikel, deleteArtikel, viewArtikelAdd, viewArtikelEdit } = require('../controller/artikelController')

router.get('/', viewIndex)
router.get('/auth', redirectRoute, authView)
router.get('/produk', protectRoute, viewProduk)
router.get('/ulasan', protectRoute, viewUlasan)
router.get('/token', protectRoute, getCode)
router.get('/artikel', protectRoute, viewArtikel)
router.get('/artikelAdd', protectRoute, viewArtikelAdd)
router.get('/accsetting', protectRoute, updateView)
router.get('/pagesetting', protectRoute, viewPageSetting)
router.get('/showArtikel/:id', artikelBlogView)
router.get('/artikelEdit/:id', protectRoute, viewArtikelEdit)
router.get('/artikel/delete/:id', protectRoute, deleteArtikel)
router.get('/produk/delete/:id', protectRoute, deleteProduk)
router.get('/deleteulasan/:id', protectRoute, deleteUlasan)

router.post('/auth', redirectRoute, auth)
router.post('/logout', protectRoute, logout)
router.post('/addulasan', addUlasan)
router.post('/accsetting', protectRoute, updateUser)
router.post('/produk/add', protectRoute, upload.single('image'), addProduk)
router.post('/artikelAdd/add', protectRoute, addArtikel)
router.post('/produk/update/:id', protectRoute, upload.single('image'), updateProduk)
router.post('/pagesetting/update/:id', protectRoute, upload.single('logo'), updatePage)
router.post('/artikelEdit/update/:id', protectRoute, updateArtikel)

module.exports = router
